spring.application.name=springboot-auth
spring.datasource.url=jdbc:sqlite:./data/mydb.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082
jwt.secret=GoRnCvVMOD0eSGturTSyAl4BnxsKkmCU8RuGCf7Y9I6trCBvRWypnlDenzrQmzC6fp2d5tto6nfskCjET0Xtsw
jwt.access-token-expiration=86400000
jwt.refresh-token-expiration=604800000